confluentinc/kafka-connect-hdfs

- pom.xml
- src/main/java/io/confluent/copycat/hdfs/AvroRecordWriterProvider.java
- src/main/java/io/confluent/copycat/hdfs/CommittedFileFilter.java
- src/main/java/io/confluent/copycat/hdfs/FSWAL.java
- src/main/java/io/confluent/copycat/hdfs/FileUtils.java
- src/main/java/io/confluent/copycat/hdfs/HdfsSinkConnector.java
- src/main/java/io/confluent/copycat/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/copycat/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/copycat/hdfs/HdfsStorage.java
- src/main/java/io/confluent/copycat/hdfs/HdfsWriter.java
- src/main/java/io/confluent/copycat/hdfs/ParquetRecordWriterProvider.java
- src/main/java/io/confluent/copycat/hdfs/Storage.java
- src/main/java/io/confluent/copycat/hdfs/StorageFactory.java
- src/main/java/io/confluent/copycat/hdfs/WAL.java
- src/main/java/io/confluent/copycat/hdfs/WALEntry.java
- src/main/java/io/confluent/copycat/hdfs/WALFile.java
- src/test/java/io/confluent/copycat/hdfs/CommittedFileFilterTest.java
- src/test/java/io/confluent/copycat/hdfs/FailureRecoveryTest.java
- src/test/java/io/confluent/copycat/hdfs/HdfsSinkConnectorTestBase.java
- src/test/java/io/confluent/copycat/hdfs/HdfsSinkTaskTest.java
- src/test/java/io/confluent/copycat/hdfs/HdfsWriterTest.java
- src/test/java/io/confluent/copycat/hdfs/WALFileTest.java
- src/test/java/io/confluent/copycat/hdfs/WALTest.java
- src/test/java/io/confluent/copycat/hdfs/utils/Data.java
- src/test/java/io/confluent/copycat/hdfs/utils/MemoryRecordWriter.java
- src/test/java/io/confluent/copycat/hdfs/utils/MemoryRecordWriterProvider.java
- src/test/java/io/confluent/copycat/hdfs/utils/MemoryStorage.java
- src/test/java/io/confluent/copycat/hdfs/utils/MemoryWAL.java
@ewencp  Can you review it and provide some feedback? Thanks!
This PR adds the following functionality:
1. Time based file rotate using ScheduledExecutorService. 
2. WAL implementation to ensure exactly once delivery in case of failure and zombie writes.
TODO:
1. Replace SequenceFile class with a customized format. This PR uses the SequenceFile  implementation in hadoop trunk. 
2. WAL truncation. Currently, to make sure that we don't commit a file in WAL with a certain starting offset if there is already a committed file with the same start offset to ensure that data is not written to HDFS more than once.  This operation is relatively expensive if there are lots of committed files under a topic partition directory.  Truncating the WAL can reduce the number of such operations.  
3. Create …
> Exactly once delivery with WAL

- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
The offset should be one more than the largest offset found in the filenames
since the offset should be set to the next record to be read. Also get rid of
many +1/-1 adjustments to offset, offsets, and beginOffsets in
TopicPartitionWriter to minimize the number of places we have to adjust offset
information by 1.
> Fix off-by-one error in resetting offsets.

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
This addresses two problems. First, it guarantees that even if the set returned
by context.assignment() or in the onPartitionsAssigned/onPartitionsRevoked are
modified, the task still has the correct assignment information. Second, the set
returned by the context.assignment() method is an unmodifiable set and the
existing code was trying to modify it on rebalances. Copying it avoids this
problem.
> Ensure the connector always has its own copy of the partition assignment.

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
- src/test/java/io/confluent/connect/hdfs/avro/AvroHiveUtilTest.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/DataWriterParquetTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/ParquetHiveUtilTest.java
Instead of trying to hold onto temp files and continue using them if assigned the same partition after rebalance, just drop the temp files immediately because trying to reuse them requires a much more complicated approach and validation of the offsets since the consumer could have missed some generations of group membership.
As fallout of this change, we also no longer save in-progress work when cleanly shutting down the connector, instead always getting files of the requested size. We also validate offsets of records because of KAFKA-2894 which can result in incorrect delivery of messages to connectors that try to reset offsets during a rebalance operation.
> Drop temp files during onPartitionsRevoked to correctly handle rebalance

- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/connect/hdfs/hive/HiveMetaStore.java
We add the hive.metasore.uris config to work around a bug in HiveConf.addResource which can set the value of a configuration back to default. This is needed for connector system test to correctly pick up the right metastore. The documentation for the configurations should be improved and I will address them in later PRs. 
@ewencp Should be a quick review.
> Add hive.metastore.uris config

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/test/java/io/confluent/connect/hdfs/FailureRecoveryTest.java
- src/test/java/io/confluent/connect/hdfs/avro/AvroHiveUtilTest.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
- src/test/java/io/confluent/connect/hdfs/avro/HiveIntegrationAvroTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/DataWriterParquetTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/HiveIntegrationParquetTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/ParquetHiveUtilTest.java
@ewencp @hachikuji No need to close writers again as we already have it closed in `onPartitionRevoked`.
> Remove close of topic partition writers in DataWriter close

- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
@ewencp The current validation logic may not work on HDFS when the connect principal have no access to HDFS's root directory.
> Remove HdfsUrlValidator

- pom.xml
- src/main/java/io/confluent/connect/hdfs/DataWriter.java
@ewencp There was an issue on Kerberos ticket renew for Java 8 in Hadoop 2.6.0 (https://issues.apache.org/jira/browse/HADOOP-10786). The issue is fixed in 2.6.1. Upgrading to 2.6.1 will fix the issue.
> Upgrade to Hadoop 2.6.1

- src/main/java/io/confluent/connect/hdfs/parquet/ParquetRecordWriterProvider.java
* We use Cloudera CDH distribution of Hadoop.
* Kafka connect is running in distributed mode on CDH nodes.
* HDFS is set up in high availability mode with logical name `nameservice`.
* Path to HDFS configuration files on each node is `/etc/hadoop/conf` which is managed by CDH manager. Configs are valid and command line hdfs tools work properly with them.
* HDFS Connector property `hadoop.conf.dir` is set up to the path mentioned above, `hdfs.url` is set to `hdfs://nameservice1`.
* HDFS Connector is set up to write data in parquet format.
HDFS Sink starts up and recovers partitions from HDFS. When it tries to write to HDFS we get the following exception:
```
[2016-07-13 14:35:15,221] ERROR Task test-task-connector-0 threw an uncaught and unrecoverable exception …
```
> Use configured Hadoop configuration object for Parquet writer

- src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java
- src/test/java/io/confluent/connect/hdfs/wal/FSWALTest.java
Currently, the code continues appending to log.1, so the next recovery invocation doesn't know about all those WAL entries.
I verified that the regression test fails without the patch.
> Start a new WAL file after `truncate` instead of appending to log.1

- pom.xml
- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/main/java/io/confluent/connect/hdfs/wal/WALFile.java
- src/test/java/io/confluent/connect/hdfs/FailureRecoveryTest.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
- src/test/java/io/confluent/connect/hdfs/avro/TopicPartitionWriterTest.java
- src/test/java/io/confluent/connect/hdfs/wal/WALFileTest.java
- src/test/java/io/confluent/connect/hdfs/wal/WALTest.java
All the generics changes are elided at compile time, but the WALFile patch changes the interface from Object to WALEntry. I'm not sure why this class was declared to take Object/Writable, since it seems to require WALEntry instances
(Just want to clean up my fork.)
> Fix lint annoyances

- pom.xml
@ewencp: this fixed the compiler issue we discussed. It's fixed at least on my machine.
> Lint change to avoid compiler error in Oracle JDK 1.7 using jenv.

- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
This PR is to fix the TimeBasedPartitioner validation.  Today it returns visible=false for ``partition.duration.ms`` if you call config/validate with the TimeBasedPartitioner set.  @shikhar can you review?
> Fix TimeBasedPartitioner config validation

- src/main/java/io/confluent/connect/hdfs/avro/AvroHiveUtil.java
- src/main/java/io/confluent/connect/hdfs/hive/HiveMetaStore.java
- src/main/java/io/confluent/connect/hdfs/hive/HiveUtil.java
- src/main/java/io/confluent/connect/hdfs/parquet/ParquetHiveUtil.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java
- src/test/java/io/confluent/connect/hdfs/avro/HiveIntegrationAvroTest.java
@cotedm replacement PR for https://github.com/confluentinc/kafka-connect-hdfs/pull/137
Fixes Issue #136
> Issue 136 - Support topic with dots in hive.

- pom.xml
Bumping up Hadoop version to 2.7.3
Also bumping up joda-time because it's old and has created conflicts with other packages. 
Hive doesn't need upgrade at this point.
> MINOR: Upgrade Hadoop version to 2.7.3 and joda-time to 2.9.7

- src/main/java/io/confluent/connect/hdfs/avro/AvroRecordWriterProvider.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
> Handle primitive types in AvroRecordWriterProvider.

- pom.xml
- src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java
- src/test/java/io/confluent/connect/hdfs/TestWithMiniDFSCluster.java
- src/test/java/io/confluent/connect/hdfs/avro/AvroHiveUtilTest.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
- src/test/java/io/confluent/connect/hdfs/avro/TopicPartitionWriterTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/DataWriterParquetTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/HiveIntegrationParquetTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/ParquetHiveUtilTest.java
Added a few test cases. 
But mainly adding necessary refactorings in junit tests in order to be able to write more tests and iterate easier over more records, in anticipation of additional formatters.
> CC-491: Consolidate and simplify unit tests of HDFS connector

- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTestWithSecureHDFS.java
- src/test/java/io/confluent/connect/hdfs/avro/HiveIntegrationAvroTest.java
- src/test/java/io/confluent/connect/hdfs/avro/TopicPartitionWriterTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/HiveIntegrationParquetTest.java
Related to confluentinc/kafka-connect-storage-common#53.
> Support for multiple fields in field partitioner

- src/main/java/io/confluent/connect/hdfs/string/StringFileReader.java
- src/main/java/io/confluent/connect/hdfs/string/StringFormat.java
- src/main/java/io/confluent/connect/hdfs/string/StringRecordWriterProvider.java
- src/test/java/io/confluent/connect/hdfs/string/DataWriterStringTest.java
- src/test/java/io/confluent/connect/hdfs/string/StringDataFileReader.java
- Creating StringFormat to be used with `format.class`.
- Adding tests.
> Adding StringFormat to available formatters

- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
The HDFS connector always uses an offset of 0 when resetting offsets and there is no output in HDFS for the requested topic partition. This results in the connector _always_ starting at the beginning, regardless of the `consumer.auto.offset.reset` setting.
This commit changes the behavior to not explicitly set an offset when the connector found no output in HDFS for the requested topic partition. As a result, the connector will rely upon the consumer to start where it has been configured, either the beginning if `consumer.auto.offset.reset=earliest` (which is what Connect explicitly sets by default) or at the most recent offset if `consumer.auto.offset.reset=latest` when the worker is explicitly configured this way.
Incidentally, this new behavior matches that of the S3 connector.
> CC-1669: Set no offset when no offset was found for topic partition

- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
This change allows the HDFS connector to tell Connect that consumer offsets need not be committed. 
When a new HDFS connector is started, no files are in HDFS for these topic partitions and the connector will then delegate to the consumer as to where to start. Since this PR changes the connector to have no offsets committed to `__consumer_offsets`, there will be no offsets and the consumer will start based upon the `consumer.auto.offset.reset` Connect worker setting (which Connect defaults to `earliest`), per #299.
Note: If any `__consumer_offsets` for the consumer group used by this new connector _are_ found,
the consumer will use them. This does allow a user to use the Kafka offset reset tool _before_ the connector is start to control exactly where they want the connector to begin. …
> CC-1669: Disable commit of consumer offsets

- Jenkinsfile
Since Hadoop 2.7.x is not compatible with Java 9+,
see https://github.com/elastic/elasticsearch/issues/25450
> MINOR update Jenkinsfile to use JDK8

- src/main/java/io/confluent/connect/hdfs/wal/WALFile.java
- src/test/java/io/confluent/connect/hdfs/wal/FSWALTest.java
Addresses #53
[JIRA](https://confluentinc.atlassian.net/browse/CC-274)
If the connector is killed in between creating a new log file and writing a version header to that file, it then ends up in an endless loop during the recover process where it continually tries and fails to read a version header from that file.
This fix involves performing a rudimentary check to see if the WAL file contains an empty/incomplete version header, and if so, creating a new WAL file and overwriting the existing one.
> CC-274: Recover cleanly with empty WAL file

- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
This is to fix NPE from system test:
```
2018-07-19 07:49:57,466 ERROR WorkerSinkTask{id=hdfs-sink-0}
Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NullPointerException
at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:135)
at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:376)
at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:560)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:183)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at …
```
> CC-2399: Fix NPE during close

- src/main/java/io/confluent/connect/hdfs/parquet/ParquetRecordWriterProvider.java
Prior to this change, it was possible that the creation of one Parquet writer failed, and because the HDFS connector’s `TopicPartitionWriter` attempts to retry the call, subsequent calls result in a NPE. This commit always attempts to create the `AvroParquetWriter` when needed (even on subsequent retries), and adds more logging statements to help diagnose the behavior.
> CC-2493: Improved initialization and logging of Parquet writer

- src/main/java/io/confluent/connect/hdfs/parquet/ParquetRecordWriterProvider.java
Change the `ParquetRecordWriterProvider` class to open the `AvroParquetWriter` instance for each Parquet temp file with ‘overwrite’ mode. This required using the `AvroParquetWriter.Builder` class rather than the deprecated constructor, which did not have a way to specify the mode.
The Avro format's writer already uses an "overwrite" mode, so this brings the same behavior to the Parquet format.
Note that the connector "commits" the records written to a temp file by closing it and moving it to the final location, as part of the HDFS connector's write ahead log behavior. The change in this PR is useful when the connector restarts and there's already an existing Parquet temp file; without this change a `FileAlreadyExistsException` is thrown.
> CC-2515: Open temp Parquet files with OVERWRITE mode

- src/main/java/io/confluent/connect/hdfs/avro/AvroRecordWriterProvider.java
- src/main/java/io/confluent/connect/hdfs/parquet/ParquetRecordWriterProvider.java
Small fix preventing the call to toString on each written record in parquet format. The purpose is to enhance performances when logging trace level is disabled.
Issue described in #343 .
> Fixed issue #343

- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
S3 and GCS support this feature, but HDFS does not yet
> Skip config setting for append-late-data

- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
Reverts confluentinc/kafka-connect-hdfs#367 to avoid inclusion in a release yet.
> Revert "Skip config setting for append-late-data"

- checkstyle/suppressions.xml
Caused by adding an extra line in #414, which shifted the constructor line number by one and making the suppression rule miss the constructor.
> MINOR: Correct checkstyle suppression line number for constructor

- checkstyle/suppressions.xml
- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
- src/test/java/io/confluent/connect/hdfs/avro/TopicPartitionWriterTest.java
- src/test/resources/log4j.properties
Modified the task’s `preCommit(…)` method to always return the offsets for only those records that have been committed to HDFS. Connect will then use the consumer to commit those offsets to the `__consumer_offsets` topic, which allows for simple monitoring of the approximate lag of the connector.
First, this change does not affect the HDFS connector’s exactly once behavior, because the connector still writes and uses the offsets it records in the files in HDFS; as long as these files are found in HDFS for the topic partitions, the HDFS connector will use these to determine where Connect should begin consuming. If the HDFS connector does not find the files in HDFS, it will let Connect and the consumer determine where to start, which will be based upon the committed offsets if found or upon …
> CC-3950: Change the HDFS sink task to return to Connect offsets for records committed to HDFS

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
When the HDFS Sink task is closed, it does not clear its partition assignment (something that the S3 Sink task does). This can cause an NPE since during `close` it clears the `topicPartitionWriters` but not the `assignment` that is used to iterate over `topicPartitionWriters`.
> CC-4124:  Clear partition assignment on close

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/FileUtils.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
- src/test/java/io/confluent/connect/hdfs/avro/TopicPartitionWriterTest.java
Consumer groups were reporting current-offset as one less than
log-end-offset in the fully caught-up state.
This fixes the topic's perception of current offset to match
the current offset we are storing in HDFS
> CC-4318 Fix off-by-one error for offset reporting to Kafka topic

- pom.xml
- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
• After Hive dependencies are removed from kafka-connect-storage-common package, kafka-connect-storage-hive needs to be imported explicitly. 
• After the change in Format interface, we need to explicitly cast to HiveFactory here.
> CC-4433b: Import Hive as separate package

- src/assembly/package.xml
This exclusion caused the ducker images to be built without including the new library. 
Signed-off-by: Arjun Satish <arjun@confluent.io>
> CC-4877: Include storage-hive artifacts in the assembly

- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java
This is fallout from oncall. We often have WAL recovery errors and this will help us locate the issue with higher resolution
> Adding debug logs for WAL recovery

- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/test/java/io/confluent/connect/hdfs/CustomPartitionerPropertiesTest.java
The HDFS connector currently passes all of its known connector properties to the partitioner, but extra properties not known to the connector are excluded. With this change, the connector will also pass any extra connector configuration properties to the partitioner.
Added a unit test to verify that a custom partitioner will see the extra properties. This new test failed before the `HdfsSinkConnectorConfig` code was changed, and now passes.
> CC-5969: Pass extra connector configs to the partitioner

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
Changed the task to throw an exception if the task could not be started successfully. In some cases, an exception would be logged but not re-thrown.
Also checked for null references in a couple of places that can result from an improperly-started or failing task.
> CC-6089: Improve fault tolerance of HDFS sink connector

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/connect/hdfs/hive/HiveUtil.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfigTest.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskWithSecureHDFSTest.java
- src/test/java/io/confluent/connect/hdfs/TestWithSecureMiniDFSCluster.java
`hfds.url` was deprecated everywhere in the documentation for `store.url` but it was not reflected in the code and results in NPE
addresses the issue in [DOCS-1449](https://confluentinc.atlassian.net/browse/DOCS-1449)
and [here](https://confluentinc.atlassian.net/browse/CC-6196) 
> CC-6196: fix NPE for store.url config

- pom.xml
- src/test/java/io/confluent/connect/hdfs/avro/HiveIntegrationAvroTest.java
- src/test/java/io/confluent/connect/hdfs/hive/HiveTestBase.java
- src/test/java/io/confluent/connect/hdfs/parquet/HiveIntegrationParquetTest.java
- src/test/resources/conf/hive-site.xml
Rely on version picked up from parent `kafka-connect-storage-common` instead of explicitly specifying Hadoop version here.
Also, updates tests to pass with newer versions of Hadoop/Hive that are introduced in https://github.com/confluentinc/kafka-connect-storage-common/pull/123
> [6.0] MINOR: remove explicit Hadoop versioning

- pom.xml
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/FailureRecoveryTest.java
- src/test/java/io/confluent/connect/hdfs/utils/Data.java
- src/test/java/io/confluent/connect/hdfs/utils/MemoryRecordWriterProvider.java
- src/test/java/io/confluent/connect/hdfs/utils/MemoryWAL.java
Exceptions thrown from time-based commits (in particular exceptions from appending to the WAL) aren't retried effectively, leading to corrupted files. 
* When an exception is thrown during time-based commits, the state machine is still updated to WRITE_STARTED
* When recovering in a subsequent non-empty write, the WRITE_STARTED state triggers the writer to start a new file, since the previous file was closed but not committed.
* This leads to the loss of the contents of the previous file, and corruption of the current file's offsets.
This test setup expects that the files 0-2, 3, 4-6 are created, but without the accompanying fix in the TopicPartitionWriter, the files 0-2 and 3-5 are created, and the 3-5 file is missing record 3, which was delivered in the initial batch and then …
> CC-9710: Retry effectively on exceptions from time-based commits

- src/test/java/io/confluent/connect/hdfs/FailureRecoveryTest.java
#477 changed `topicsDir` to be a hashmap and #503 introduced a new test that relied on `topicsDir` as a string
fetch the desired string from the map
make sure the connector compiles and builds
issue is found in `5.5.x`
> MINOR: fix build error from bad merge

- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/FailureRecoveryTest.java
Sometimes closing a temporary file fails, which means the file does not get flushed properly and therefore may result empty or corrupted files in HDFS showing up. 
If a temporary file does not close the file, the connector will take the most conservative approach and will delete the temporary file attempt to rewrite all the records from scratch.
Note that this PR does not address closing temporary files when closing the `TopicPartitionWriter`. That should be addressed in a different PR.
HDFS3 could face a similar issue
Added a unit test that makes sure that the connector correctly handles the offsets and close failures. 
I also ran manual tests where I simulated closing failures (5% of the time) and see how the connector addresses them. They were a success.
Backporting to 5.0.x when this …
> CC-7360: Recover gracefully if closing a temporary file fails

- pom.xml
`hadoop 2.7.3` is depending on a `beanutils 1.7.0` which has security vulnerabilites. 
Bumping to `2.10.0` imports `1.9.4` which resolves these issues and also addresses hadoop CVEs
EDIT: new approach pinning `beanutils` and bumping to `2.7.7`
`5.4.x` where the CVE was discovered
> [ci-skip] bump hadoop version to address beanutils CVE

- pom.xml
Vulnerable dependency `io.netty_netty:3.6.2.Final` and `io.netty_netty-all:4.0.23.Final`. 
Exclude the affected dependencies.
Backporting to 5.4.x
> Resolving netty CVEs

- Jenkinsfile
- pom.xml
We need the release maven plugin for independent releases. Also, some adjustment in version variables
Add the plugin and apply fixes
In all community available connectors formerly shipping with CP
master only. 10.0.x will be created after this commit.
> CC-11858: Add release maven plugin and prepare 10.0 release

- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/avro/AvroFormat.java
- src/main/java/io/confluent/connect/hdfs/parquet/ParquetFormat.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java
HDFS connector configurations, specifically connect.meta.data and enhanced.avro.schema.support essentially NOOP when configured; they are ignored when AvroData is configured.
Use fix from https://github.com/confluentinc/kafka-connect-hdfs/pull/327
> Fix #326 by using config's avroDataConfig method

- src/main/java/io/confluent/connect/hdfs/avro/AvroHiveUtil.java
- src/main/java/io/confluent/connect/hdfs/parquet/ParquetHiveUtil.java
- src/test/java/io/confluent/connect/hdfs/avro/HiveIntegrationAvroTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/HiveIntegrationParquetTest.java
Duplicate columns are created when the field partitioner is used. 
Remove duplicate column instances.
Could not backport to a earlier branch as MiniDFSCluster tests are unstable on older branches.
> CC-12567: Fix duplicate columns in Hive for Parquet and Avro formats

- pom.xml
Some dependencies bring shaded jackson with them. And these jackson versions are older and have CVEs
We reshaded the dependencies in storage-common. This PR uses these jars instead and we are also using the recently released 10.0.0 of storage-common for that purpose. 
10.0.0 of hdfs will be released soon after we merge here.
> Import CVE-free htrace-core4 and avatica from kafka-connect-storage-common

- pom.xml
build is broken due to jamon dep
bump storage common version that contains fix https://github.com/confluentinc/kafka-connect-storage-common/pull/169
`10.0.x` where build is broken
> MINOR: bump storage common version

- src/test/java/io/confluent/connect/hdfs/TestWithMiniDFSCluster.java
- src/test/java/io/confluent/connect/hdfs/TestWithSecureMiniDFSCluster.java
when running all the tests together in Intellij the Kerberos tests interfere with the non-Kerberos tests and cause them fail because the UserGroupInformation is set by the connector and that is a static instance
reset the UGI between each test
bonus: refactored the tests to take 30 seconds down from 7 minutes by reusing a HDFS instance for each test
HDFS3 has the same issue
run all previous tests and make sure they are green when run simultaneously 
`10.0.x` is earliest because `reset()` isn't provided in earlier Hadoop versions
> CC-13111: fix Kerberos tests interfering with non-Kerberos tests

- src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java
- src/main/java/io/confluent/connect/hdfs/wal/WALFile.java
```
09:28:12.741 [task-thread-ConnectorName-0] ERROR io.confluent.connect.hdfs.wal.WALFile - Failed creating a WAL Writer: Failed to APPEND_FILE /abc/4/log for DFSClient on 10.10.10.10 because this file lease is currently owned by DFSClient on 10.10.10.11
[2021-02-01 09:28:12,741] INFO Cannot acquire lease on WAL, ConnectorName-0, file hdfs://abc/4/log (io.confluent.connect.hdfs.wal.FSWAL)
```
The error message above (on not being able to acquire a lease) is expected when one task is waiting for another task to release the `WAL` file. Both messages refer to the same issue, but are logged at different log levels. 
Both messages should be logged on the same level, and not `ERROR` level as this is an expected behavior when leases are held. An exception is thrown later if there is a retry …
> CCMSG-857: Match lease acquisition log level

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/main/java/io/confluent/connect/hdfs/hive/HiveUtil.java
- src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfigTest.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java
HDFS connector uses an outdated approach of fetching the configs directly
replace with getters for readability 
storage common
run existing tests to ensure no regressions
backport to `5.0.x` to remove merge conflicts
> MINOR: add getters for hdfs configs

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java
* Constructor in `DataWriter` is hard to read and uses an all-encompassing try block that should be broken up to improve legibility and error handling. 
* `FSWAL` code needs a minor refactor in `apply` to make code more readable and prepare for upcoming changes. 
* `HdfsSinkTask` and `FSWAL` do not adhere to logging standards and could use improved logging.  
* Break constructor in `DataWriter` into smaller logical units, and split the try block to improve legibility and error handling. 
* Refactor `FSWAL` and add improved logging. 
* Add improved logging to `HdfsSinkTask` .  
This PR is scoped for review convenience and further refactors may follow. 
Backporting to `5.5.x` where `CorruptWalFileException` was added.
> MINOR: Refactor code for readability and add improved logging

- pom.xml
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java
- src/main/java/io/confluent/connect/hdfs/wal/WALFile.java
- src/test/java/io/confluent/connect/hdfs/utils/MemoryWAL.java
- src/test/java/io/confluent/connect/hdfs/wal/FSWALTest.java
The HDFS connector tracks Kafka offsets through the names of the files written to HDFS. 
1. On startup, the connector attempts to recover the most recently committed offsets by recursively scanning the `topics.dir` for each topic partition it has been assigned, and then resumes consuming from those offsets. 
2. On write, when the schema is initialized the connector performs the same recursive search. 
The recursive file listing operation becomes expensive when there are thousands or millions of files and the connector takes a long time to start. 
Use the stored offsets from the `WAL` file as a primary method for recovery. Fall-back on the current approach as a backup and for backwards compatibility when the `WAL` is not readable or non-existent. 
**Summary of functional changes** …
> CCMSG-670: Use WAL file as primary for offset recovery

- src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java
- src/test/java/io/confluent/connect/hdfs/wal/FSWALTest.java
During task restart or connector configuration change, CannotObtainBlockLengthException can happen during WAL file apply. 
```
ERROR [90455_DMZ_fedd_hdfs_sink_testing_04_23_2021|task-0] Error applying WAL file: hdfs://SFP-UAT/tenants/90455/shared/gti_dbus_dmz/logs/topic-rl-100031-89345/7/log, {} (io.confluent.connect.hdfs.wal.FSWAL:156)
org.apache.hadoop.hdfs.CannotObtainBlockLengthException: Cannot obtain block length for LocatedBlock{BP-679409434-169.84.229.54-1449158097549:blk_2272402293_1199287568; getBlockSize()=6407; corrupt=false; offset=0; locs=[DatanodeInfoWithStorage[169.127.76.17:50010,DS-bc4eba2c-a5e0-46da-824d-3bd9c3c0da2e,DISK], DatanodeInfoWithStorage[169.84.230.15:50010,DS-bf60049b-1981-490a-9b16-04f8d563bf63,DISK], …
```
> CCMSG-953: work around wal CannotObtainBlockLengthException

- checkstyle/suppressions.xml
- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/main/java/io/confluent/connect/hdfs/tools/SchemaSourceTask.java
- src/test/java/io/confluent/connect/hdfs/TopicPartitionWriterTest.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
the connector still uses java7 style when it can be updated to rely on java8 features
TPWTest was in the wrong package
move TPWTest to the root package and and replace java7 language features with java8
run existing tests
> MINOR: adopt java8 features and cleanup

- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/TopicPartitionWriterTest.java
the connector [keeps track of offsets incorrectly](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java#L883) by doing `offset = offset + recordCounter`
this makes the assumption that record offsets increment by 1 which is wrong
because offsets can increase by more than 1. imagine the scenario of a compacted topic which goes from 1 2 3 4 5 6 7 8 9 10 to 2 4 8 10, 10 records to 4, the starting offset is 1 + 10 = 11 is next offset which is correct but after compaction its 1 + 4 = 5, which is wrong. We would be repeating two extra records (8, 10).
keep track of the latest offset by getting the largest end offset committed in the group of files committed
caveats: …
> CCMSG-1004: fix incorrect TopicPartitionWriter internal offset tracking

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/test/java/io/confluent/connect/hdfs/FailureRecoveryTest.java
- src/test/java/io/confluent/connect/hdfs/FormatAPIDataWriterCompatibilityTest.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskWithSecureHDFSTest.java
- src/test/java/io/confluent/connect/hdfs/avro/AvroHiveUtilTest.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
- src/test/java/io/confluent/connect/hdfs/avro/HiveIntegrationAvroTest.java
- src/test/java/io/confluent/connect/hdfs/json/DataWriterJsonTest.java
- src/test/java/io/confluent/connect/hdfs/orc/DataWriterOrcTest.java
- src/test/java/io/confluent/connect/hdfs/orc/HiveIntegrationOrcTest.java
- src/test/java/io/confluent/connect/hdfs/orc/OrcHiveUtilTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/DataWriterParquetTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/HiveIntegrationParquetTest.java
- src/test/java/io/confluent/connect/hdfs/parquet/ParquetHiveUtilTest.java
- src/test/java/io/confluent/connect/hdfs/string/DataWriterStringTest.java
The connect framework calls `open(Collection<TopicPartition> partitions)` in order to provide the assigned partitions for the task. However, the code is also attempting to fetch the assigned partitions information in `start()` via  `context.assignment()` from the `SinkTaskContext`. This only works for testing purposes as the context passed there is mocked. In the real calls when starting the connector, `context.assignment()` will come in empty in `start()` as the connect framework has not yet assigned the partitions. The partitions are only assigned on `open()`.
This is due to the fact that `context.assigment()` is not initialized until at least one `put()` call has returned, which means that referencing `context.assigment()` in `start()` is incorrect as it will always be empty. This has …
> CC-14408: Fix empty context assignment in start()

- pom.xml
updating `storage-common` to include https://github.com/confluentinc/kafka-connect-storage-common/pull/191
> CCMSG-1072: bump storage-common to include necessary jackson mapper dependency

- pom.xml
The current version doesn't package `jackson-mapper-asl` JAR.
It's included as a transitive `test` dependency only:
```
...
[INFO] +- org.apache.hadoop:hadoop-minicluster:jar:2.10.1:test
[INFO] |  +- org.apache.hadoop:hadoop-common:test-jar:tests:2.10.1:test
[INFO] |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.1.1:compile
[INFO] |  |  +- xmlenc:xmlenc:jar:0.52:compile
[INFO] |  |  +- commons-net:commons-net:jar:3.1:compile
[INFO] |  |  +- javax.servlet:servlet-api:jar:2.5:compile
[INFO] |  |  +- org.mortbay.jetty:jetty:jar:6.1.26:compile
[INFO] |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |  |  +- org.mortbay.jetty:jetty-sslengine:jar:6.1.26:compile
[INFO] |  |  +- javax.servlet.jsp:jsp-api:jar:2.1:runtime
[INFO] …
```
> CCMSG-1202: Use kafka-connect-storage-common:10.1.1.

- src/main/java/io/confluent/connect/hdfs/storage/HdfsStorage.java
- src/main/java/io/confluent/connect/hdfs/wal/WALFile.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
- src/test/java/io/confluent/connect/hdfs/TestWithMiniDFSCluster.java
- src/test/java/io/confluent/connect/hdfs/TestWithSecureMiniDFSCluster.java
- src/test/java/io/confluent/connect/hdfs/wal/FSWALTest.java
- src/test/java/io/confluent/connect/hdfs/wal/WALFileTest.java
HDFS client has a cache - `org.apache.hadoop.fs.FileSystem#CACHE`.
It's not automatically cleaned, it requires an explicit cleanup.
In the HDFS sink connector, some actions create new entries in the cache and some clean entries from it(added comments in the code, to make review easier, will remove before merging).
`io.confluent.connect.hdfs.wal.FSWAL#FSWAL` does actions, that create cache entries:
- `append()`
- `acquireLease()`
- `apply()`
- `truncate()`
Whenever we call `org.apache.hadoop.fs.FileSystem#newInstance(java.net.URI, org.apache.hadoop.conf.Configuration)`, it creates one entry in `org.apache.hadoop.fs.FileSystem#CACHE` so it has to be closed when not needed anymore.
There is a `catch` clause in `io.confluent.connect.hdfs.wal.WALFile.Writer#Writer`, that closes `fs` in case …
> CCMSG-1014: Do not leak fs in io.confluent.connect.hdfs.wal.WALFile.Writer#Writer().

- pom.xml
Rebasing https://github.com/confluentinc/kafka-connect-hdfs/pull/585 for 5.2.x
Import htrace shaded dependency as seperate package
Tested with docker playground
```
prathibha@C02DV6PDMD6T  ~/git/go/src/github.com/confluentinc/kafka-docker-playground   master export CONNECTOR_ZIP=/Users/prathibha/git/go/src/github.com/confluentinc/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-5.2.6-SNAPSHOT.zip
prathibha@C02DV6PDMD6T  ~/git/go/src/github.com/confluentinc/kafka-docker-playground/connect/connect-hdfs2-sink   master ./hdfs2-sink.sh
18:11:58 ℹ️ 💫 Using CP version 6.2.0
18:11:58 ℹ️ 🎓 set TAG environment variable to specify different version
18:12:00 ℹ️ 🚀 CONNECTOR_ZIP is set with /Users/prathibha/git/go/src/github.com/confluentinc/kafka-connect-hdfs/target …
```
> CCMSG-1344: Use htrace shaded dependency 

- pom.xml
CVE fix for netty codec 4.1.63.Final
Netty codec dependency is excluded from a transitive pull.
> CCMSG-1406 | Exclude netty codec dependency for CVE fix.

- pom.xml
Security Vulnerability in log4j dependency. Versions 2.15.0+ are acceptable.
Security Vulnerability in log4j dependency - log4j-api-2.8.2.jar and log4j-core-2.8.2.jar
Versions 2.15.0+ are acceptable.
(by following example from https://github.com/confluentinc/kafka-connect-gcp-dataproc/pull/65)
Bump up log4j-api alongside the corresponding slf4j dependency (log4j-slf4j-impl) as certain classes (ex ReflectionUtil) are deprecated in 2.14.0 - we need to be at 2.15.0.
Also bumping for com.lmax:disruptor dependency from 3.3.0 to 3.4.2, similar to dataproc
> Bump up the dependency for log4j to 2.15.0

- pom.xml
Update log4j to use confluent-log4j version 1.2.17-cp2.2
```bash
mvn dependency:tree  | grep log4j
[INFO] |  |  +- log4j:apache-log4j-extras:jar:1.2.17:compile
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.26:compile
```
```bash
[colivier@chriso-monster:kafka-connect-hdfs (colivier/5.3.x)]mvn dependency:tree | grep log4j
[INFO] |  |  +- log4j:apache-log4j-extras:jar:1.2.17:compile
[INFO] +- io.confluent:confluent-log4j:jar:1.2.17-cp2.2:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.26:compile
```
> CC-15907 Update log4j to use confluent-log4j version 1.2.17-cp2.2

- src/main/java/io/confluent/connect/hdfs/DataWriter.java
The Hadoop DFS client auto closes and created clients, when the JVM shuts down. This can happen prior to the connector being closed, which requires these clients to be in open state for deletion of temporary files on close. Note that this error only comes into the picture when the connect worker is stopped/restarted. 
Hadoop has a configuration `fs.automatic.close` which is by default true. Setting this as `false` will disable this behaviour. This is safe to do as we are anyways not relying on the auto close feature for closing all the clients. The connector lifecycle has appropriate routines for closing these clients on exit since it needs to rely on the lifecycle during a a connector delete, where the JVM shut down hooks are not executed. The connector should always operate with …
> FIX: Set fs.automatic.close to false in Hadoop configuration

- pom.xml
The following CVEs were scanned by a customer.
https://confluentinc.atlassian.net/browse/CCMSG-1900
https://confluentinc.atlassian.net/browse/CCMSG-1901
https://confluentinc.atlassian.net/browse/CCMSG-1904
https://confluentinc.atlassian.net/browse/CCMSG-1908
https://confluentinc.atlassian.net/browse/CCMSG-1910
https://confluentinc.atlassian.net/browse/CCMSG-1912
Since all of these dependencies are brought in through hive we have to override those dependencies through dependency management. Some of the dependencies can be removed. The changes were done in storage-common in https://github.com/confluentinc/kafka-connect-storage-common/pull/238 and the version is bumped here.
> CCMSG-1906: Address CVEs for ant, jsp, groovy, derby, netty and orc.

- pom.xml
we cant go to v30+ due to incompatible interfaces. v18 is a lot older google library
and we know this is only used in tests so we explicitly mark the dependency to test scope thereby dodging the CVE
`CONNECTOR_ZIP=/Users/parag.badani/git/go/src/github.com/confluentinc/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.1.9-SNAPSHOT.zip ./hdfs2-source
`
```
16:11:24 ℹ️ 💫 Using default CP version 7.1.1
16:11:24 ℹ️ 🎓 set TAG environment variable to specify different version, see https://kafka-docker-playground.io/#/how-to-use?id=🎯-for-confluent-platform-cp
16:11:24 ℹ️ 👷🛠 Re-building Docker image vdesabou/kafka-docker-playground-connect:7.1.1 to include confluentinc/kafka-connect-hdfs:latest
[+] Building 39.8s (6/6) FINISHED …
```
> CCMSG-1794 | CVE fix for guava dependency.

- pom.xml
Current kafka connect storage common uses protobuf-java 3.1.0 which has a vulnerability.
Updated kafka connect storage common version to fix the CVE
Docker playground output:
```
➜  connect-hdfs2-sink git:(master) ✗ CONNECTOR_ZIP=/Users/ajain/projects/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.0.9-SNAPSHOT.zip ./hdfs2-sink.sh
20:17:08 ℹ️ 💫 Using default CP version 7.1.1
20:17:08 ℹ️ 🎓 set TAG environment variable to specify different version, see https://kafka-docker-playground.io/#/how-to-use?id=🎯-for-confluent-platform-cp
20:17:08 ℹ️ 👷🛠 Re-building Docker image vdesabou/kafka-docker-playground-connect:7.1.1 to include confluentinc/kafka-connect-hdfs:latest
[+] Building 53.9s (6/6) FINISHED
=> [internal] load build definition from Dockerfile …
```
> CCMSG-1793: Update dependencies to fix protobuf cve and integration tests

- pom.xml
Hadoop version 2.10.1 has the following CVEs. 
https://confluentinc.atlassian.net/browse/CCMSG-2025
https://confluentinc.atlassian.net/browse/CCMSG-2023
https://confluentinc.atlassian.net/browse/CCMSG-2017
https://confluentinc.atlassian.net/browse/CCMSG-2015
The version of hadoop was upgraded in https://github.com/confluentinc/kafka-connect-storage-common/pull/253. Bumping up the parent pom version here.
> CCMSG-2015: Address CVEs with hadoop verision 2.10.1

- pom.xml
This parent bump brings in a derby version upgrade for a CVE fix.
> CCMSG-1908: Bump parent to 11.0.13.

- pom.xml
woodstox-core:5.3.0 and jettison:1.1 are vulnerable. 
Pin woodstox-core:6.5.0 and jettison:1.5.3 to fix the CVE
> CC-18964  CCMSG-2421 CCMSG-2420  Update Ivy, commons-net, json-smart, mina-core and xmlbuilder 

- pom.xml
CVE fixes for
https://confluentinc.atlassian.net/browse/CC-20975
https://confluentinc.atlassian.net/browse/CC-20976  
https://confluentinc.atlassian.net/browse/CC-20328
HDFS2 Sink
```
vbalani@Vikass-MacBook-Pro connect-hdfs2-sink % playground run -f hdfs2-sink.sh --connector-zip /Users/vbalani/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.2.3-SNAPSHOT.zip
09:59:07 ℹ️ 🚀 Running example with flags
09:59:07 ℹ️ ⛳ Flags used are  --connector-zip=/Users/vbalani/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.2.3-SNAPSHOT.zip
09:59:08 ℹ️ 💀 Kill all docker containers
09:59:14 ℹ️ ####################################################
09:59:14 ℹ️ 🚀 Executing hdfs2-sink.sh in dir .
09:59:14 ℹ️ …
```
> CVE fixes: jackson-core, snappy

- pom.xml
CVE fixes: 
https://confluentinc.atlassian.net/browse/CC-22575
https://confluentinc.atlassian.net/browse/CC-22217
Updated version of ivy and snappy-java to version without cves.
CVE is not showing in the PR scan: https://twistlock.tools.confluent-internal.io/#!/monitor/vulnerabilities/images/ci?search=Confluent%20Public%20Repo%20PR%20builder%2Fkafka-connect-hdfs%2FPR-672
Dependency tree, the version is  updated
```
ksoneji@T9X6X34XJG kafka-connect-hdfs % mvn dependency:tree | grep -e snappy -e ivy
[INFO] |  |  \- org.xerial.snappy:snappy-java:jar:1.1.10.4:compile
[INFO] |  |  +- org.apache.ivy:ivy:jar:2.5.2:compile
```
Unit tests:
```
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 151, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```
Docker playground
```
Docker playground test …
```
> [CC-22217, CC-22575] CVE Fixes

- src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
- src/main/java/io/confluent/connect/hdfs/avro/AvroIOException.java
- src/main/java/io/confluent/connect/hdfs/avro/AvroRecordWriterProvider.java
- src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
A [change](https://issues.apache.org/jira/browse/AVRO-2109) was introduced into the avro writer where it resets its internal buffer of records on receiving an IOException. This differed from the earlier model where a IOException would not clear out the existing buffer. Due to this there is a potential for data loss in the connector as it does not rewrite the topic data into the buffer even on getting an IOException. Once the avro writer recovers the connector will flush the buffer and commit the offsets ignoring the previously missed data.
This can only happen on the avro writer and the connector needs to rewind back the offsets of the topic partition and recover the buffer if such a situation arises. This PR addresses the changes required for this contingency by capturing the …
> RCCA-16236: AVRO buffer loss fix on IOException 

- pom.xml
https://confluentinc.atlassian.net/browse/CC-22821
https://confluentinc.atlassian.net/browse/CC-22940
https://confluentinc.atlassian.net/browse/CC-23101
https://confluentinc.atlassian.net/browse/CC-23261
https://confluentinc.atlassian.net/browse/CC-25320
Docker Playground Test: https://github.com/confluentinc/kafka-connect-hdfs/pull/688#issuecomment-2007807860
```
Twistlock Scan
jar	 critical	org.apache.hadoop_hadoop-hdfs version 2.10.2 has 1 vulnerability
jar	 critical	org.apache.hadoop_hadoop-common version 2.10.2 has 1 vulnerability
jar	 critical	org.apache.calcite_calcite-core version 1.11.0 has 2 vulnerabilities
jar	 high	org.xerial.snappy_snappy-java version 1.1.10 has 4 vulnerabilities <--- Twistlock does not pick up nano-versions. This has already been fixed
jar	 high …
```
> CVE Fixes: Avro, Netty, Zookeeper, Compress

- pom.xml
> CC-26343: Exclude `commons-httpclient` to fix CVE

- pom.xml
[CC-26341](https://confluentinc.atlassian.net/browse/CC-26341), [CC-26346](https://confluentinc.atlassian.net/browse/CC-26346): Fix CVEs in `jackson-databind` and `netty-codec-http` by bumping kafka-connect-storage-common.
[CC-27071](https://confluentinc.atlassian.net/browse/CC-27071): Pin `avatica-core` and bump `calcite-core` & `calcite-druid` to highest version compatible with hive
[CC-26343](https://confluentinc.atlassian.net/browse/CC-26343): Pin `apache-hbase` to exclude `common-httpclients`
[CC-26342](https://confluentinc.atlassian.net/browse/CC-26342): Pin `nimbus-jose-jwt` with non-vulnerable version
[CC-26345](https://confluentinc.atlassian.net/browse/CC-26345): Pin `okio` with non-vulnerable version
Test 1: https://github.com/confluentinc/kafka-connect-hdfs/pull/693#issuecomment …
> CC-26341, CC-26342, CC-26343, CC-26345, CC-26346, CC-27071: CVE Fixes

- pom.xml
CC-27233 - Bump kafka-connect-storage-common version to fix CVE
```
> playground run -f hdfs2-sink.sh --connector-zip ~/gitrepos/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.2.8-SNAPSHOT.zip
16:03:52 ℹ️ 🚀 Running example with flags
16:03:52 ℹ️ ⛳ Flags used are --connector-zip=/Users/vbalani/gitrepos/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.2.8-SNAPSHOT.zip
16:03:53 ℹ️ 💀 Kill all docker containers
16:04:02 ℹ️ 📋 command to run again example has been copied to the clipboard (disable with 'playground config set clipboard false')
16:04:03 ℹ️ 🚀 Number of examples ran so far: 36
16:04:03 ℹ️ ####################################################
16:04:03 ℹ️ 🚀 Executing hdfs2-sink.sh in dir .
16:04:03 ℹ️ …
```
> CC-27233: Bump kafka-connect-storage-common version to fix CVE

- pom.xml
* Pin `aircompressor` to `v0.27.0` to fix [CVE-2024-36114](https://nvd.nist.gov/vuln/detail/CVE-2024-36114)
* Bump `libthrift` version to `v0.14.0` and `kafka-connect-storage-common-version` to `11.2.16` fix [CVE-2020-13949](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-13949)
```
> playground run -f hdfs2-sink.sh --connector-zip ~/gitrepos/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.2.8-SNAPSHOT.zip
15:59:05 ℹ️ 🚀 Running example with flags
15:59:05 ℹ️ ⛳ Flags used are --connector-zip=/Users/vbalani/gitrepos/kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.2.8-SNAPSHOT.zip
15:59:05 ℹ️ 💀 Kill all docker containers
15:59:08 ℹ️ 📋 command to run again example has been copied to the clipboard (disable with …
```
> CVE Fix: libthrift, aircompressor

- pom.xml
CVE Tickets:
https://confluentinc.atlassian.net/browse/CC-29302 : [CVE-2024-7254](https://nvd.nist.gov/vuln/detail/CVE-2024-7254)
https://confluentinc.atlassian.net/browse/CC-29425 : [CVE-2024-47554](https://nvd.nist.gov/vuln/detail/CVE-2024-47554)
```
> mvn dependency:tree -Daether.dependencyCollector.impl=bf -Dmaven.artifact.threads=100   | grep -e commons-io -e protobuf-java
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.25.5:compile
[INFO] |  +- commons-io:commons-io:jar:2.14.0:compile
```
Docker playground tests
```
> cd ~/gitrepos/kafka-docker-playground/connect/connect-hdfs2-sink
> playground run -f hdfs2-sink.sh --connector-zip ~/gitrepos/airlock-kafka-connect-hdfs/target/components/packages/confluentinc-kafka-connect-hdfs-10.2.11-SNAPSHOT.zip
16:40:44 ℹ️ 🚀 Running example …
```
> CC-29302, CC-29425: CVE Fixes for `commons-io` & `protobuf-java` 

- pom.xml
* [CC-29504](https://confluentinc.atlassian.net/browse/CC-29504) : [CVE-2024-47561](https://nvd.nist.gov/vuln/detail/CVE-2024-47561): Bump kafka-connect-storage-common to update `org.apacha.avro:avro` version to `v1.11.4` 
* [CC-29566](https://confluentinc.atlassian.net/browse/CC-29566) Bump kafka-connect-storage-common to update `jetty-server` to `9.4.56.v20240826`
* [CC-29601](https://confluentinc.atlassian.net/browse/CC-29601): Bump `velocity-engine-core` to `v2.4.0` as it declares `commons-io` as a dependency and results in a false positive for CVE-2024-47554
```
>17:41:49 ℹ️ 🚦 containers have started!
17:41:49 ℹ️ 📊 JMX metrics are available locally on those ports:
17:41:49 ℹ️     - zookeeper       : 9999
17:41:49 ℹ️     - broker          : 10000
17:41:49 ℹ️     - schema-registry : …
```
> CC-29601, CC-29566, CC-29504: CVE Fixes

- pom.xml
v10.2.12 release failed midway through the process, and v10.2.12 was not made available on the confluent hub.
Revert the snapshot version to `v10.2.12-SNAPSHOT` and re-attempt the release.
> Revert release version

- src/main/java/io/confluent/connect/hdfs/FileUtils.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
- src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConstants.java
- src/main/java/io/confluent/connect/hdfs/filter/CommittedFileFilter.java
- src/main/java/io/confluent/connect/hdfs/filter/TopicCommittedFileFilter.java
- src/main/java/io/confluent/connect/hdfs/filter/TopicPartitionCommittedFileFilter.java
- src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfigTest.java
Potential ReDOS vulnerability from user-supplied data in java.util.regex in HdfsSinkConnectorConfig.java
Utilizing RE2/J, the Java implementation of the RE2 regular expression engine, as one of the recommended approaches outlined in the ticket.
Docker playground test with config: `"topic.capture.groups.regex": "^(.+)-(\\\\d{4})-(\\\\d{2})-(\\\\d{2})$"`
```
limit 10;ve2://hive-server:10000/testhive> select * from app_metrics_2025_05_21 
+----------------------------+-----------------------------------+
| app_metrics_2025_05_21.f1  | app_metrics_2025_05_21.partition  |
+----------------------------+-----------------------------------+
| value1                     | 0                                 |
| value2                     | 0                                 |
| value3 …
```
> CC-32379: Use RE2/J to address Potential ReDOS vulnerability in java.util.regex

- pom.xml
https://confluentinc.atlassian.net/browse/CC-34816
```
Name                           Status       Tasks                                                        Stack Trace
-------------------------------------------------------------------------------------------------------------
hdfs-sink                      ✅ RUNNING  0:🟢 RUNNING[connect]        -
-------------------------------------------------------------------------------------------------------------
11:21:00 ℹ️ 🌐 documentation for 🌎onprem connector kafka-connect-hdfs is available at:
https://docs.confluent.io/kafka-connect-hdfs/current/index.html
11:21:00 ℹ️ Sending messages to topic test_hdfs
11:21:01 ℹ️ 🔮 value schema was identified as avro
11:21:01 ℹ️ ✨ generating value data...
11:21:01 ℹ️ ☢️ --forced-value is set
11:21:01 ℹ️ …
```
> CC-34816: Bump jersey-core version
