confluentinc/kafka-connect-hdfs

pom.xml
src/main/java/io/confluent/copycat/hdfs/FileUtils.java
src/main/java/io/confluent/copycat/hdfs/HdfsSinkConnectorConfig.java
src/main/java/io/confluent/copycat/hdfs/HdfsStorage.java
src/main/java/io/confluent/copycat/hdfs/hive/HiveExec.java
src/main/java/io/confluent/copycat/hdfs/hive/HiveQLWriter.java
src/test/java/io/confluent/copycat/hdfs/HdfsSinkConnectorTestBase.java
src/test/java/io/confluent/copycat/hdfs/hive/HiveExecTest.java

This PR adds necessary utilities to import files in HDFS to Hive. 
@ewencp Can you take a look at it when you hive time? It's based on the WAL branch, but all the changes related to Hive are in the hive directory.

Hive import

---

pom.xml
src/main/java/io/confluent/connect/hdfs/DataWriter.java
src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTestWithSecureHDFS.java
src/test/java/io/confluent/connect/hdfs/TestWithSecureMiniDFSCluster.java

@ewencp @gwenshap Added secure HDFS support.

Add secure HDFS support

---

config/connect-hdfs-sink.properties
src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java

@ewencp Time based file rotation.

Add timebased file rotation

---

src/main/java/io/confluent/connect/hdfs/DataWriter.java
src/main/java/io/confluent/connect/hdfs/HdfsSinkConnecorConstants.java
src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java

@ewencp Moves tempfiles to topicsDir/tmp. Unit test passes on my machines.

Move tempfiles to separate directory

---

docs/index.rst

@ewencp Minor doc fix to make sure the index is displayed properly.

Minor doc fix

---

docs/index.rst

Fixed "TimebasedPartitioner" references to "TimeBasedPartitioner".

Minor doc typo fix TimeBasedPartitioner

---

src/main/java/io/confluent/connect/hdfs/hive/HiveMetaStore.java

Removing retry logic from HiveMetaStore to fix the metastore connection bloat

---

docs/hdfs_connector.rst

added notes for properly configuring hdfs-connect for HA hdfs.

HA HDFS config

---

docs/configuration_options.rst
src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java

Re-generated using `ConfigDef.toEnrichedRst()` (with a local Kafka build containing https://github.com/apache/kafka/pull/1964)

CC-331: Update config options docs

---

README.md

Updated Readme for Kafka connect FAQ

Updated Readme for Kafka connect FAQ

---

docs/hdfs_connector.rst

fixed avro-tools command in docs

updated avro-tools instructions in doc

---

src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java

This has been fixed since 0.10.1, so it has been long enough to allow for compatibility.

Remove invalid offset check.

---

src/test/java/io/confluent/connect/hdfs/partitioner/TimeUtils.java

fix TimeBasedPartitionerTest by defining the expected locale

---

docs/changelog.rst

Includes PR #247 that has yet to be merged.

CC-1250: 4.0.0 release notes

---

docs/hdfs_connector.rst

Made this an include, so that an easy update going forward. See source: https://github.com/confluentinc/docs/blob/master/includes/installation.rst

Make confluent CLI command output shared

---

docs/hdfs_connector.rst

Related https://github.com/confluentinc/docs/pull/807

Fix for moved /includes content

---

src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskWithSecureHDFSTest.java
src/test/java/io/confluent/connect/hdfs/TestWithMiniDFSCluster.java
src/test/java/io/confluent/connect/hdfs/TestWithSecureMiniDFSCluster.java

This test was broken and not running because the file did not end with
*Test.java

MINOR: Fix the secure HDFS test

---

docs/index.rst

https://confluentinc.atlassian.net/browse/DOCS-647

DOCS-647 Add HDFS Connector URL to the docs

---

src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java

This adds trace messages to rotation checks to help with customer issues.

CC-2797:  Add trace messages for rotations

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/hdfs/DataWriter.java
src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java
src/main/java/io/confluent/connect/hdfs/avro/AvroHiveUtil.java
src/main/java/io/confluent/connect/hdfs/parquet/ParquetHiveUtil.java
src/test/java/io/confluent/connect/hdfs/FailureRecoveryTest.java
src/test/java/io/confluent/connect/hdfs/FormatAPITopicPartitionWriterCompatibilityTest.java
src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java
src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskTest.java
src/test/java/io/confluent/connect/hdfs/HdfsSinkTaskWithSecureHDFSTest.java
src/test/java/io/confluent/connect/hdfs/TestWithMiniDFSCluster.java
src/test/java/io/confluent/connect/hdfs/avro/DataWriterAvroTest.java
src/test/java/io/confluent/connect/hdfs/avro/HiveIntegrationAvroTest.java
src/test/java/io/confluent/connect/hdfs/avro/TopicPartitionWriterTest.java
src/test/java/io/confluent/connect/hdfs/parquet/HiveIntegrationParquetTest.java
src/test/java/io/confluent/connect/hdfs/wal/WALFileTest.java
src/test/java/io/confluent/connect/hdfs/wal/WALTest.java

see CC ticket and relevant one pager for explanation

CC-7247: allow topics.dir config to be more configurable

---

Jenkinsfile

Dependencies built from these projects were found in this project. Changes in these upstream projects may not appear in your build in a timely manner without these changes.
Please edit the suggestion before merging, and if you wish to disable this bot, select Disable.
Created by jenkinsfile-rewriter.

CC-6409: Update Jenkinsfile for 3.3.x

---

src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfigTest.java

MINOR: add orc format to configs

---

src/main/java/io/confluent/connect/hdfs/DataWriter.java

Signed-off-by: Greg Harris <gregh@confluent.io>

CC-8809: Replace assignment with topicPartitionWriters.keySet

---

src/main/java/io/confluent/connect/hdfs/wal/WALFile.java

Signed-off-by: Greg Harris <gregh@confluent.io>

MINOR: Fix WALFile javadoc issues

---

pom.xml
src/main/java/io/confluent/connect/hdfs/orc/OrcUtil.java

MINOR: Fix javadoc warnings and define version for storage-common

---

pom.xml

Update docs URL path to exact path (currently its redirecting but we're updating now to have a clean trail)
Please let me know if I should target a different branch for this one and will do if needed.
Update docs URL path to exact path

update pom.xml URL path

---

pom.xml

CCMSG-779: Update kafka-connect-storage-common-parent to 10.0.4 to resolve CVE.

---

src/main/java/io/confluent/connect/hdfs/HdfsSinkConnector.java
src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java
src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java
src/main/java/io/confluent/connect/hdfs/wal/FSWAL.java

MINOR: Add task.id and additional logging when requesting a lease

---

src/test/java/io/confluent/connect/hdfs/TopicPartitionWriterTest.java

MINOR: fix build

---

pom.xml

lots of CVEs
resolve using various techniques
https://github.com/confluentinc/kafka-connect-storage-common/pull/185 should resolve a lot of them
jetty is being addressed by https://github.com/confluentinc/kafka-connect-storage-common/pull/190
only unresolvable CVEs are: 
- guava
- asl
- thrift

CC-14520: fix jackson and hadoop CVEs

---

pom.xml

Update storage common to 10.1.2

---

pom.xml

bump log4j version to 2.16.0

---

pom.xml

Client requested update to latest version of log4j
Update log4j to latest (2.17.1)

CCMSG-1615 Update log4j to latest (2.17.1)

---

pom.xml

CC-16542 Add log4j2 core

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 10.0.x to 10.1.x)

---

pom.xml

CVE https://confluentinc.atlassian.net/browse/CCMSG-1901
Remove ant dependency. It may be good to remove the ant dependency from parent but raising this PR so that tests can run and we can check if we can actually remove the dependency.

Remove ant dependency

---

pom.xml
src/main/java/io/confluent/connect/hdfs/avro/AvroRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/json/JsonRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/parquet/ParquetRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/string/StringRecordWriterProvider.java

* removed record logs
* updated maven url
* fix dependencies

CCMSG-2091: Removed logging of records (#632)

---

src/main/java/io/confluent/connect/hdfs/avro/AvroRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/json/JsonRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/parquet/ParquetRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/string/StringRecordWriterProvider.java

remove logging of sensitive customer data. https://confluentinc.atlassian.net/browse/CCMSG-2109

removed logging from different writer providers

---

pom.xml

CVE fix for netty, calcite and avatica-core
https://confluentinc.atlassian.net/browse/CCMSG-2174
https://confluentinc.atlassian.net/browse/CCMSG-2154
storage-commons changes
https://github.com/confluentinc/kafka-connect-storage-common/pull/288

CCMSG-2154, CCMSG-2174 cve fix for netty

---

src/main/java/io/confluent/connect/hdfs/avro/AvroRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/json/JsonRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/parquet/ParquetRecordWriterProvider.java
src/main/java/io/confluent/connect/hdfs/string/StringRecordWriterProvider.java

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
merge conflict resolve as part of https://github.com/confluentinc/kafka-connect-hdfs/pull/637/files
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or …

Merge Conflict Resolution (from 4.1.x to 5.0.x)

---

pom.xml

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 10.1.x to 10.2.x)

---

pom.xml

Master build earlier had failed because pint merge from 10.1.x wasn't done and changes from 10.1.x were not present in 10.2.x.
Manually merged the changes from 10.2.x to 10.2.x

Merge10.2.x 10.1.x

---

.semaphore/semaphore.yml
Jenkinsfile
service.yml

* Add service.yml
* Delete Jenkinsfile
* chore: update repo semaphore config
---------

Cherry-Pick "Jenkins->Semaphore Migration (#686)" to Legacy Feature Branches

---

Jenkinsfile
pom.xml
sonar-project.properties

This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall

Merge Conflict Resolution (from 5.2.x to 5.3.x)

---

pom.xml

CC-27071: Fix CVEs in `avatica-core` by pinning the dependency + Updating calcite-core to latest supported version

---

pom.xml

CC-26345: Pin `okio` version to fix CVE

---

.semaphore/semaphore.yml
sonar-project.properties

This is a routine update from cc-service-bot based on the service.yml in your repo. This PR
should be approved and merged as soon as CI passes.

chore: update repo by service bot

---

pom.xml

* Bump kafka-connect-storage-common versioin
* Bump libthrift
https://github.com/confluentinc/kafka-connect-hdfs/pull/726#issuecomment-2778487057

CC-33022, CC-33021: Bump Kafka Connect Storage Common & Libthrift [10.1.x]

---

pom.xml

* Bump kafka connect storage common
https://github.com/confluentinc/kafka-connect-hdfs/pull/727#issuecomment-2778632822

CC-33022, CC-33021: Bump Kafka Connect Storage Common [10.2.x] 

---

pom.xml

Exclude protobuf converter dependency
```
> mvn dependency:tree -Daether.dependencyCollector.impl=bf -Dmaven.artifact.threads=1000 -Dincludes=io.confluent:kafka-connect-protobuf-converter
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: aarch_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 15.1
[INFO] os.detected.version.major: 15
[INFO] os.detected.version.minor: 1
[INFO] os.detected.classifier: osx-aarch_64
[INFO] 
[INFO] ------------------< io.confluent:kafka-connect-hdfs >-------------------
[INFO] Building …
```

Exclude Protobuf Converter Dependency

---

.semaphore/semaphore.yml

Upgrade Ubuntu Instance Used in CI
